import { RouteStatus, SafetyReport } from '@/types';

export const INITIAL_ROUTES: RouteStatus[] = [
  {
    id: 'route-north-gate',
    name: 'Market Central to North Gate',
    description: 'Main commercial exit connecting the market stalls to the northern residential quarters. Amara\'s typical route home.',
    status: 'SAFE',
    confidenceScore: 88,
    lastUpdated: '6:38 PM (2 mins ago)',
    firsthandCount: 3,
    hearsayCount: 0,
    summary: 'Clear transit confirmed by multiple vendors and riders leaving the market. No blockages reported.',
    activeIncidents: ['Normal traffic movement', 'Market exit gate open and clear'],
  },
  {
    id: 'route-east-bridge',
    name: 'Eastern River Bypass & Bridge',
    description: 'Secondary crossing towards the eastern farmland and outer ring road.',
    status: 'CAUTION',
    confidenceScore: 42,
    lastUpdated: '6:25 PM (15 mins ago)',
    firsthandCount: 0,
    hearsayCount: 2,
    summary: 'Unverified WhatsApp forwards allege group gathering near the bridge pillar. No firsthand witness has verified this claim.',
    activeIncidents: ['Unverified gathering claim', 'Awaiting direct verification'],
  },
  {
    id: 'route-south-highway',
    name: 'South Highway Junction (Kilometer 4)',
    description: 'Interstate transport route connecting to the southern district.',
    status: 'DANGER',
    confidenceScore: 94,
    lastUpdated: '6:18 PM (22 mins ago)',
    firsthandCount: 4,
    hearsayCount: 1,
    summary: 'Confirmed roadblock and vehicle diversions reported by multiple drivers and local radio.',
    activeIncidents: ['Active vehicle diversion', 'Roadway impassable for civilian cars'],
  },
];

export const INITIAL_REPORTS: SafetyReport[] = [
  {
    id: 'rep-001',
    rawText: 'Just left market through North Gate on my bike at 6:32 PM. Road is completely clear, shops along the street are closing normally.',
    submittedAt: '6:33 PM',
    location: 'Market Central to North Gate',
    sourceType: 'FIRSTHAND_OBSERVATION',
    incidentType: 'Normal Passage',
    claim: 'Road is clear and safe for transit with normal activity.',
    confidenceScore: 95,
    urgency: 'LOW',
    needsHumanReview: false,
    isFirsthand: true,
    reasoning: 'Eyewitness report with exact timestamp, direct travel mode, and specific ground details.',
    verifiedByAi: true,
  },
  {
    id: 'rep-002',
    rawText: 'WARNING FORWARDED: My cousin said someone posted on family group that bad boys are blocking Eastern Bridge right now! Do not go there!!',
    submittedAt: '6:25 PM',
    location: 'Eastern River Bypass & Bridge',
    sourceType: 'UNVERIFIED_WHATSAPP',
    incidentType: 'Alleged Roadblock',
    claim: 'Unconfirmed claim of unrest at Eastern Bridge.',
    confidenceScore: 28,
    urgency: 'MEDIUM',
    needsHumanReview: true,
    isFirsthand: false,
    reasoning: 'Hearsay chain: cousin quoting another group forward without direct observation or verifiable location details.',
    verifiedByAi: true,
  },
  {
    id: 'rep-003',
    rawText: 'Community patrol radio broadcast (Channel 4): South Highway Kilometer 4 is closed due to emergency security diversion. Divert to North Gate.',
    submittedAt: '6:18 PM',
    location: 'South Highway Junction (Kilometer 4)',
    sourceType: 'COMMUNITY_RADIO',
    incidentType: 'Official Road Closure',
    claim: 'South Highway closed by security personnel.',
    confidenceScore: 92,
    urgency: 'HIGH',
    needsHumanReview: false,
    isFirsthand: true,
    reasoning: 'Verified patrol channel broadcast instructing civilian detour away from South Highway.',
    verifiedByAi: true,
  },
  {
    id: 'rep-004',
    rawText: 'Tricycle driver Musa here: Drove 2 passengers to North Gate just now at 6:38 PM. Normal flow, streetlights are on, gate is open.',
    submittedAt: '6:38 PM',
    location: 'Market Central to North Gate',
    sourceType: 'FIRSTHAND_OBSERVATION',
    incidentType: 'Clear Route Confirmation',
    claim: 'North Gate corridor has active traffic and open gate.',
    confidenceScore: 96,
    urgency: 'LOW',
    needsHumanReview: false,
    isFirsthand: true,
    reasoning: 'Direct commercial driver firsthand observation confirming safe transit.',
    verifiedByAi: true,
  },
];

export const PRESET_SAMPLE_REPORTS = [
  {
    title: 'Firsthand Driver Update (North Gate)',
    text: 'I just drove my truck past North Gate road at 6:42 PM. Road is totally clear, vigilante post gave thumbs up, no delays.',
    expectedRoute: 'Market Central to North Gate',
    hint: 'Firsthand observation with high confidence score.',
  },
  {
    title: 'Frantic WhatsApp Rumor (Eastern Bridge)',
    text: 'URGENT PLEASE SHARE: My neighbour said her sister heard gunshots near the eastern bridge area! Stay indoors everyone panic!!',
    expectedRoute: 'Eastern River Bypass & Bridge',
    hint: 'Classic second-hand panic forward. AI flags as hearsay with low confidence.',
  },
  {
    title: 'Vigilante Patrol Radio Alert (South Road)',
    text: 'Vigilante Unit 2 reporting from South Road junction: Fallen tree and military checkpoint blocking lane. All cars must turn back.',
    expectedRoute: 'South Highway Junction (Kilometer 4)',
    hint: 'Direct radio report with high urgency and high confidence.',
  },
];
